### ISSUE TITLE
Video not playing in the Videos Page

### ISSUE THREAD

**Issue by himalimehta** [phuselab/DANTE#4]
@vcuculo hi, I added myself as the first annotator to annotate 3 videos in the alpha directory. 

Upon doing this, I was given the following notification on the page: "New annotator added, please copy and send the personal URL:" I then copy+pasted this personal url to another window in my browser and was able to see the list of videos on the left side of the page. The issue I am facing is that I am unable to start the video and watch it. This is what I see on the page:

![videos](https://user-images.githubusercontent.com/77561854/106218540-78da4280-61a5-11eb-9a94-1832c7a2ae0b.png)

What could be the reason behind this?

Also, where will I be able to see the values for annotation of each video (valence and arousal values)? 

Do my other annotators need to install any requirements in order to annotate the videos from the video directory they are assigned?

**Comment by vcuculo** [comment]
@himalimehta glad to hear that you were able to solve all the configuration issues! 

> What could be the reason behind this?

As regard the missing video, the reason is that HTML5 video tag supports only specific video formats (more info [here](https://en.wikipedia.org/wiki/HTML5_video#Browser_support)).
In particular it supports: Theora (Ogg), H.264 (MP4), HEVC (MP4), VP8 (WebM), VP9 (WebM), AV1 (WebM).
For a wider compatibility I suggest you to convert your AVI files to H.264 (MP4) file format. You can easily do it, with a software (such as Handbrake) or with a cloud-base solution (like [this](https://cloudconvert.com/avi-to-mp4))

> Also, where will I be able to see the values for annotation of each video (valence and arousal values)?

It depends on the value of `save_mode` in the `config.php` file. If you set it to `db`, the annotations will be saved in the `annotation` table, and you can retrieve them with a simple SQL query. If you set it to `file`, the annotations will be saved in `csv` files inside the `annotation` folder. Before using file mode, check the permission of the `annotation` folder.

> Do my other annotators need to install any requirements in order to annotate the videos from the video directory they are assigned?

Nothing else than a web browser.

**Comment by himalimehta** [comment]
@vcuculo I will convert my AVI files to H.264 (MP4) file format and see how it works. 

I would actually like to save the annotation values in a csv file so I will make sure to change the value of save_mode from “db” to “file” in config.php, but just wondering, how will the annotation folder be created? Does that have to be created manually inside the www folder? 

Additionally, I noticed that valence and arousal are annotated separately in DANTE, so is it possible to retrieve each video’s valence and arousal values in the same csv file? For example, I’d like the csv file to have two columns: “valence” and “arousal” and the rows following after that will have the values ranging between -1 and 1, depending on how the particular video has been annotated.

**Comment by vcuculo** [comment]
@himalimehta 

> I would actually like to save the annotation values in a csv file so I will make sure to change the value of save_mode from “db” to “file” in config.php, but just wondering, how will the annotation folder be created? Does that have to be created manually inside the www folder?

If the `annotation` folder does not exists, the application will create it for you. 

> Additionally, I noticed that valence and arousal are annotated separately in DANTE, so is it possible to retrieve each video’s valence and arousal values in the same csv file? For example, I’d like the csv file to have two columns: “valence” and “arousal” and the rows following after that will have the values ranging between -1 and 1, depending on how the particular video has been annotated.

Since the annotator performs the annotation of valence and arousal in two different moments, DANTE does create two different files for each dimension. If you really need that feature, you can dig and edit this method https://github.com/phuselab/DANTE/blob/b10e3931fc476b15d5ad11cec8e6bfe47c0c29b4/model.php#L66 which is where the annotations are being saved.
